### ISSUE TITLE
Plugin seems broken with Brave

### ISSUE THREAD

**Issue by pierce403** [aquiladev/remix-mythx-plugin#37]
When loading remix while the mythx plugin is installed, I get this errror in the console, and the mythx interface is completely blank. I feel like it was working last week with the same setup. Things seem to work fine with Firefox on the same laptop. The issue persists even with the Brave Shield down.

Using Brave v0.70.106 on Ubuntu 19.04.

```
react-dom.production.min.js:4408 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new a (https://remix-mythx-plugin.surge.sh/static/js/main.8db018bb.chunk.js:1:2585)
    at ui (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:381196)
    at Co (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:396055)
    at Ro (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:402570)
    at Ya (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:426579)
    at Ga (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:426963)
    at js (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:434001)
    at Ms (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:433381)
    at Ts (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:432402)
    at es (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:431269)
da @ react-dom.production.min.js:4408
react-dom.production.min.js:5940 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new a (https://remix-mythx-plugin.surge.sh/static/js/main.8db018bb.chunk.js:1:2585)
    at ui (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:381196)
    at Co (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:396055)
    at Ro (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:402570)
    at Ya (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:426579)
    at Ga (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:426963)
    at js (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:434001)
    at Ms (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:433381)
    at Ts (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:432402)
    at es (https://remix-mythx-plugin.surge.sh/static/js/2.eb506c2d.chunk.js:1:431269)
Ms @ react-dom.production.min.js:5940
Ts @ react-dom.production.min.js:5860
es @ react-dom.production.min.js:5787
Us @ react-dom.production.min.js:6077
zs @ react-dom.production.min.js:6085
Vs.render @ react-dom.production.min.js:6276
(anonymous) @ react-dom.production.min.js:6360
Ls @ react-dom.production.min.js:6007
Ws @ react-dom.production.min.js:6359
render @ react-dom.production.min.js:6390
397 @ index.js:7
i @ (index):1
183 @ main.8db018bb.chunk.js:1
i @ (index):1
f @ (index):1
e @ (index):1
(anonymous) @ main.8db018bb.chunk.js:1
```

**Comment by aquiladev** [comment]
It is a known issue with Brave. I'll take a look

**Comment by aquiladev** [comment]
@pierce403 
Solution: Set `Cookies` setting to `Allow all cookies` on `chrome://settings/shields` page
